remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Projects
description: My name is Jacob. This is my GitHub page giving a quick brief of my projects
